//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webappAnsTiss.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissCancelaGuia_tissCancelaGuia {
            get {
                return ((string)(this["webappAnsTiss_wsTissCancelaGuia_tissCancelaGuia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissComunicacaoBeneficiario_tissComunicacaoBeneficiario {
            get {
                return ((string)(this["webappAnsTiss_wsTissComunicacaoBeneficiario_tissComunicacaoBeneficiario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissLoteAnexo_tissLoteAnexo {
            get {
                return ((string)(this["webappAnsTiss_wsTissLoteAnexo_tissLoteAnexo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissLoteGuias_tissLoteGuias {
            get {
                return ((string)(this["webappAnsTiss_wsTissLoteGuias_tissLoteGuias"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissRecursoGlosa_tissRecursoGlosa {
            get {
                return ((string)(this["webappAnsTiss_wsTissRecursoGlosa_tissRecursoGlosa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissSolicitacaoDemonstrativoRetorno_tissSolicitacaoDemonstrativoRetorno {
            get {
                return ((string)(this["webappAnsTiss_wsTissSolicitacaoDemonstrativoRetorno_tissSolicitacaoDemonstrativoR" +
                    "etorno"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsSolicitacaoProcedimento_tissSolicitacaoProcedimento {
            get {
                return ((string)(this["webappAnsTiss_wsSolicitacaoProcedimento_tissSolicitacaoProcedimento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissSolicitacaoStatusAutorizacao_tissSolicitacaoStatusAutorizacao {
            get {
                return ((string)(this["webappAnsTiss_wsTissSolicitacaoStatusAutorizacao_tissSolicitacaoStatusAutorizacao" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissSolicitacaoStatusProtocolo_tissSolicitacaoStatusProtocolo {
            get {
                return ((string)(this["webappAnsTiss_wsTissSolicitacaoStatusProtocolo_tissSolicitacaoStatusProtocolo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissSolicitacaoStatusRecursoGlosa_tissSolicitacaoStatusProtocoloRecurso {
            get {
                return ((string)(this["webappAnsTiss_wsTissSolicitacaoStatusRecursoGlosa_tissSolicitacaoStatusProtocoloR" +
                    "ecurso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string webappAnsTiss_wsTissVerificaElegibilidade_tissVerificaElegibilidade {
            get {
                return ((string)(this["webappAnsTiss_wsTissVerificaElegibilidade_tissVerificaElegibilidade"]));
            }
        }
    }
}
